[package]
name = "htlc_contract"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.15.1"  # Updated to latest for compatibility
borsh = "1.5.1"
sha2 = "0.10.8"
base64 = "0.22.1"