[package]
name = "near-escrow-src"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.15.1"
sha2 = "0.10.8"
borsh = "1.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
